# Generated by Django 6.0.6 on 2026-08-25 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.CharField(default='Não informado', max_length=200)),
                ('turma', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id_atividade', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mentoria',
            fields=[
                ('id_mentoria', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('carga_horaria', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id_certificado', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.CharField(max_length=200)),
                ('instituicao', models.CharField(max_length=200)),
                ('carga_horaria', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMSHub.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Horas',
            fields=[
                ('id_horas', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMSHub.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id_notificacao', models.AutoField(primary_key=True, serialize=False)),
                ('mensagem', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('lida', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id_participacao', models.AutoField(primary_key=True, serialize=False)),
                ('horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('presenca', models.BooleanField()),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMSHub.aluno')),
                ('id_mentoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMSHub.mentoria')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor'), ('coordenador', 'Coordenador'), ('supervisor', 'Supervisor'), ('empresa', 'Empresa')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='AMSHub.perfil')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to='AMSHub.perfil'),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id_portfolio', models.AutoField(primary_key=True, serialize=False)),
                ('resumo', models.TextField()),
                ('aprendizados', models.TextField()),
                ('avaliacao', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMSHub.aluno')),
                ('id_mentoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMSHub.mentoria')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id_professor', models.AutoField(primary_key=True, serialize=False)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='AMSHub.perfil')),
            ],
        ),
        migrations.AddField(
            model_name='mentoria',
            name='id_professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AMSHub.professor'),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id_supervisor', models.AutoField(primary_key=True, serialize=False)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='AMSHub.perfil')),
            ],
        ),
        migrations.AddField(
            model_name='mentoria',
            name='id_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AMSHub.supervisor'),
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id_vaga', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('requisitos', models.CharField(max_length=500)),
                ('data_limite', models.DateField()),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMSHub.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id_viagem', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=200)),
                ('horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMSHub.empresa')),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMSHub.aluno')),
            ],
        ),
    ]
