# Generated by Django 6.1.2 on 2026-10-09 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMSHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='AMSHub.empresa'),
        ),
        migrations.AddField(
            model_name='mentoria',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentorias', to='AMSHub.empresa'),
        ),
    ]
