# Generated by Django 6.1 on 2026-09-01 13:18

# usuarios de testes fixos 

#TODOS OS USUSARIOS TEM A SENHA "123"

from django.db import migrations
from django.contrib.auth.hashers import make_password


def criar_usuarios_teste(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Perfil = apps.get_model('AMSHub', 'Perfil')

    usuarios = [
        ('aluno', 'aluno'),
        ('professor', 'professor'),
        ('coord', 'coordenador'),
        ('supervisor', 'supervisor'),
        ('empresa', 'empresa'),
    ]

    for username, tipo in usuarios:
        usuario, criado = User.objects.get_or_create(
            username=username
        )

        if criado:
            usuario.password = make_password('123')
            usuario.save()

        Perfil.objects.get_or_create(
            user=usuario,
            defaults={'tipo': tipo}
        )


def remover_usuarios_teste(apps, schema_editor):
    User = apps.get_model('auth', 'User')

    User.objects.filter(
        username__in=[
            'aluno',
            'professor',
            'coord',
            'supervisor',
            'empresa',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('AMSHub', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            criar_usuarios_teste,
            remover_usuarios_teste
        ),
    ]
